"""api group api and column metadata updated

Revision ID: a4a4a230dcbc
Revises: ba34d7e8f16b
Create Date: 2024-07-25 00:29:34.123423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a4a230dcbc'
down_revision: Union[str, None] = 'ba34d7e8f16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_api_groups_id'), 'api_groups', ['id'], unique=False)
    op.create_table('api_group_table_association',
    sa.Column('api_group_id', sa.Integer(), nullable=False),
    sa.Column('table_metadata_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_group_id'], ['api_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_metadata_id'], ['table_metadata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('api_group_id', 'table_metadata_id')
    )
    op.create_table('apis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['api_group_id'], ['api_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apis_id'), 'apis', ['id'], unique=False)
    op.add_column('column_metadata', sa.Column('unique', sa.Boolean(), nullable=True))
    op.add_column('column_metadata', sa.Column('default', sa.Text(), nullable=True))
    op.add_column('column_metadata', sa.Column('autoincrement', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('column_metadata', 'autoincrement')
    op.drop_column('column_metadata', 'default')
    op.drop_column('column_metadata', 'unique')
    op.drop_index(op.f('ix_apis_id'), table_name='apis')
    op.drop_table('apis')
    op.drop_table('api_group_table_association')
    op.drop_index(op.f('ix_api_groups_id'), table_name='api_groups')
    op.drop_table('api_groups')
    # ### end Alembic commands ###
