"""metadata tables

Revision ID: ba34d7e8f16b
Revises: 6f50223b9977
Create Date: 2024-07-20 13:41:43.132939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba34d7e8f16b'
down_revision: Union[str, None] = '6f50223b9977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_metadata_id'), 'table_metadata', ['id'], unique=False)
    op.create_table('column_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('nullable', sa.Boolean(), nullable=True),
    sa.Column('primary_key', sa.Boolean(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['table_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_metadata_id'), 'column_metadata', ['id'], unique=False)
    op.create_table('foreign_key_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('referenced_table', sa.String(), nullable=False),
    sa.Column('referenced_column', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['column_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_key_metadata_id'), 'foreign_key_metadata', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foreign_key_metadata_id'), table_name='foreign_key_metadata')
    op.drop_table('foreign_key_metadata')
    op.drop_index(op.f('ix_column_metadata_id'), table_name='column_metadata')
    op.drop_table('column_metadata')
    op.drop_index(op.f('ix_table_metadata_id'), table_name='table_metadata')
    op.drop_table('table_metadata')
    # ### end Alembic commands ###
